name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_run:
    workflows: ["Update"]
    branches: [master]
    types: 
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'

    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: npm install
      run: npm install
      
    - name: npm run buildGit
      run: npm run buildGit
      
    - name: push changes to remote
      run: |
        git config --global user.name "wvanderp"
        git config --global user.email "wouterv.dplas@gmail.com"

    - name: git add
      run: git add build && git commit -m "Initial build subtree commit"

    - name: git push
      run: |
        git subtree split --prefix build -b gh-pages
        git push -f origin gh-pages:gh-pages
        git branch -D gh-pages
