name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'

    - name: npm install
      run: npm install
      
    - name: npm run build
      run: npm run build
      
    - name: push changes to remote
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: git add
      run: git add build && git commit -m "Initial build subtree commit"

    - name: git push
      run: git subtree push --prefix build origin gh-pages
